### ISSUE TITLE
wrong description

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-htaccess#15]
for "Domainspezifische Regeln" ... it's the same as ".gz Rewrite"

**Comment by cliffparnitzky** [comment]
Es geht um den Text: https://github.com/hofff/contao-htaccess/blob/3.x/module/languages/de/tl_htaccess.php#L135

@frontendschlampe : Was müsste dann da hin?

Das hier waren mal die Texte in der früheren Version: https://github.com/hofff/contao-htaccess/blob/2.x/system/modules/htaccess/languages/de/tl_htaccess.php#L123

**Comment by frontendschlampe** [comment]
Das müssen wir uns mal genau ansehen und uns mal was einfallen lassen ... das ist nämlich irgendwie strange
