### ISSUE TITLE
Regel zum Umleiten auf Hauptdomain bei Aufruf von meine-domain.com/index.php 

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-htaccess#17]
Es wäre schön, wenn man eine Checkbox hätte, die man anhaken kann, um die folgende Umleitung zu setzen: 

`RewriteCond %{THE_REQUEST} ^[A-Z]+\ /index\.php`
`RewriteRule ^index\.php/?(.*) /$1? [L,R=301]`

**Comment by cliffparnitzky** [comment]
Im BE in der Section "Rewrite Modul" am Ende (nach "Contao Rewrite Suffix") einfügen:

Checkbox "Bei Aufruf von index.ph auf Startseite umleiten"
--> setzt o.g. Text als  letzte RewriteCond (letzte der automatischen RCs, vor den eigen RCs)
