### ISSUE TITLE
Funktioniert auf 3.4.4 nicht.

### ISSUE THREAD

**Issue by l0wskilled** [hofff/contao-htaccess#21]
```
Fatal error: Uncaught exception Exception with message Cannot find editor configuration file "codeMirror.php" thrown in system/modules/core/classes/DataContainer.php on line 453
#0 system/modules/core/drivers/DC_File.php(255): Contao\DataContainer->row()
#1 system/modules/core/classes/Backend.php(622): Contao\DC_File->edit()
#2 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('htaccess')
#3 contao/main.php(20): Contao\BackendMain->run()
#4 {main}
```

**Comment by KlausGrenoble** [comment]
in meiner 3.4.5 auch nicht. Why ?

**Comment by frontendschlampe** [comment]
Wir die Erweiterung ja von Tristan übernommen und sind leider bisher noch nicht dazu gekommen, sie uns genauer anzuschauen und eventuelle Fehler zu beheben. Wir hoffen aber, dass wir nach der Konferenz zeitnah die Zeit finden werden. Vielen Dank für Euer Verständnis.

**Comment by l0wskilled** [comment]
codeMirror muss mit ace ausgetauscht werden.
Bei Version 3.5 kann dc-general nicht installiert werden, weil das nur <3.5 zulässt. jedoch nutzt htaccess in der tl_htaccess.php die general klasse.

**Comment by l0wskilled** [comment]
@frontendschlampe codeMirror muss mit ace|html ausgetauscht werden. dc-general ist nur bis <3.5 verfügbar. Musst du wohl warten bis da was geht.

@KlausGrenoble Ich habe bei der non-composer Version den Editor angepasst, musst du manuell installieren wenn du es dringend brauchst. https://github.com/l0wskilled/contao-htaccess-working-with-3.5

**Comment by cliffparnitzky** [comment]
Hab die aktuelle Version unter Contao 3.5.0 und 3.5.6 installiert und läuft .... ALLERDINGS nur mit    `contao-community-alliance/dc-general : dev-hotfix/2.0.0-beta34`.

Insofern kann der Issue geschlossen werden.

**Comment by frontendschlampe** [comment]
na sehr gut ... dann hoffen wir, dass der DCG bald veröffentlicht wird
