### ISSUE TITLE
Update composer dependencies

### ISSUE THREAD

**Issue by cliffparnitzky** [hofff/contao-htaccess#22]
> Package bit3/php-string-builder is abandoned, you should avoid using it. Use bit3/string-builder instead.

**Comment by cliffparnitzky** [comment]
The commit fcffe3b26eb2167d02aff57ef38c1960af6334af also belongs to the issue.

**Comment by cliffparnitzky** [comment]
@frontendschlampe is it okay to close this issue as solved and create a new tag (3.0.2) ???

**Comment by frontendschlampe** [comment]
yes ... no problem

**Comment by cliffparnitzky** [comment]
Done

**Comment by frontendschlampe** [comment]
I think, now there's a problem after the update:

``` php
Fatal error: Class 'StringBuilder' not found in /htdocs/composer/vendor/hofff/contao-htaccess/src/Htaccess.php on line 52
```

**Comment by cliffparnitzky** [comment]
urgs, i deleted the tag and will fix this soon.

**Comment by cliffparnitzky** [comment]
Should be fixed now with 51a44695c5f255afddfbf05f511870b9a8ed3fc5

**Comment by frontendschlampe** [comment]
next time, please don't delete the tag, fix the problem and add the same tag again, because composer don't check the files of the version again. So when I have a Contao installation where I installed the version of extension with errors, Composer will not install the new version! @backbone87 can tell you more about it! ;-)

**Comment by frontendschlampe** [comment]
next time, fix the problem and make a new tag/version ;-)

**Comment by backbone87** [comment]
composer doesnt check the commit ref, if you install the dist archive, thats why he doesnt update from tag 3.0.2 of commit X to tag 3.0.2 of commit Y
