### ISSUE TITLE
Regel zum Erlauben des LetsEncrypt Bots

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-htaccess#23]
```RewriteRule "^.well-known/acme-challenge" - [L]```

Dieser Eintrag muss direkt nach ```RewriteBase```

**Comment by cliffparnitzky** [comment]
Im BE in der Section "Rewrite Modul" am Ende (nach "Contao Rewrite Suffix" einfügen:

- Checkbox "LetsEncrypt Bots erlauben"
--> setzt o.g. Text dirket nach `RewriteBase`
